# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastpage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
