# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_lastpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastpage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
