# Generated by Django 2.0.3 on 2018-03-13 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171212_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
