# Generated by Django 2.0.3 on 2018-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180313_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
